# Generated by Django 4.1 on 2022-08-23 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeIngredients',
        ),
    ]
