# Generated by Django 4.1 on 2022-08-22 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Difficult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Noob', 'Noob'), ('Master', 'Master'), ('Ninja', 'Ninja')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('calories', models.IntegerField()),
                ('cooking_time', models.TimeField()),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.difficult')),
            ],
        ),
    ]
