# Generated by Django 4.1 on 2022-08-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_ingredients_ingredient'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['product', 'recipe'], name='recipes_ing_product_dd1e5b_idx'),
        ),
    ]
