# Generated by Django 4.1 on 2022-08-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_ingredient_recipes_ing_product_dd1e5b_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ingredient',
            name='recipes_ing_product_dd1e5b_idx',
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['recipe'], name='recipes_ing_recipe__fac781_idx'),
        ),
    ]
