# Generated by Django 4.1 on 2022-08-29 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_ingredient_recipes_ing_recipe__fac781_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ingredient',
            name='covering_index',
        ),
    ]
