# Generated by Django 4.2.4 on 2023-08-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookingstep',
            name='display_id',
            field=models.IntegerField(default=1),
        ),
    ]
