# Generated by Django 4.2.4 on 2023-08-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_cookingstep_display_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookingstep',
            name='display_id',
        ),
        migrations.AlterField(
            model_name='cookingstep',
            name='step',
            field=models.IntegerField(default=1),
        ),
    ]
